// =====================================================================
// Module: ITSM proposal Logic App -- Jalon 10, step 10.2
// Every 5 minutes, takes the rows of the `itsmtickets` table that have no
// proposal yet (written by itsm/poll/), and for each ticket:
//   1. gathers DIRECTORY FACTS deterministically from Microsoft Graph
//      (subject user, directory roles, groups, manager, licences, tenant
//      licence seats) -- read-only, via the Logic App's managed identity;
//   2. asks GPT-4o (temperature 0, strict JSON schema, closed enum of
//      actions: mfa_reset, password_reset, group_add, license_assign,
//      offboarding, escalate) to classify the ticket and extract fields.
//      The model never chooses an API call and never sees a secret;
//   3. applies DETERMINISTIC GUARDS (Logic App expressions, no LLM):
//        security -> status "refused":
//          target_privileged_role     reset on an account holding an Entra directory role
//          target_is_not_requester    reset asked for someone else's account
//          secret_requested_for_third_party
//          requester_not_manager      offboarding not requested by the subject's Entra manager
//          group_not_allowlisted      group_add outside allowedGroups
//        operational -> status "needs_human":
//          already_member, no_free_license_seat, llm_escalated, low_confidence (< 0.6),
//          subject_not_found_in_entra
//        none -> status "pending_review" (waits for a human agent in the app, step 10.3);
//   4. merges the proposal back into the same table row.
// Nothing is executed on Entra ID or ServiceNow here (steps 10.3/10.4).
//
// Zero-connector design (same as ingestion/ and itsm/poll/). The workflow
// JSON is generated by gen_workflow.py -- edit that file, then re-run it.
//
// Graph application permissions (Directory.Read.All) cannot be granted by
// ARM/Bicep: run scripts/itsm/grant-graph-app-roles.ps1 with the output
// principal id after the first deployment (runbook 11.5).
// =====================================================================

param clientCode string = 'itsm-demo'
param location string = resourceGroup().location
param namePrefix string = 'knowledgeengine3'
param storageAccountName string = 'st${namePrefix}v9'
param tableName string = 'itsmtickets'
param foundryName string = 'aif-${namePrefix}-v9'

@description('GPT-4o deployment used for classification (pinned version, see infra/modules/foundry.bicep)')
param aoaiDeployment string = 'gpt-4o'

@description('Azure OpenAI API version supporting response_format json_schema')
param aoaiApiVersion string = '2024-10-21'

@description('Groups the module may propose to add a user to (allowlist enforced by a deterministic guard)')
param allowedGroups array = [
  { name: 'SG-SP-Projets', description: 'Acces au site SharePoint Projets (documents de chantier)' }
  { name: 'SG-VPN-Users', description: 'Acces VPN' }
  { name: 'SG-App-Planning', description: 'Acces a l application Planning' }
]

param createRoleAssignments bool = true

@description('false on a FIRST deployment (Graph app roles not granted yet, runbook 11.5); true when redeploying once they are')
param startEnabled bool = false

var logicAppName = 'logic-itsm-propose-${clientCode}'
var storageTableDataContributorRoleId = '0a9a7e1f-b9d0-4cc4-a60d-0319b160aaa3'
var cognitiveServicesOpenAIUserRoleId = '5e0bd9bd-7b93-4f28-af87-19fc36ad61bd'

resource storageAccount 'Microsoft.Storage/storageAccounts@2023-01-01' existing = {
  name: storageAccountName
}

resource foundry 'Microsoft.CognitiveServices/accounts@2025-04-01-preview' existing = {
  name: foundryName
}

resource logicApp 'Microsoft.Logic/workflows@2019-05-01' = {
  name: logicAppName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    // Created DISABLED on a first deployment: the Graph app roles must be granted first
    // (runbook 11.5), otherwise every run fails on Graph 403 until then.
    state: startEnabled ? 'Enabled' : 'Disabled'
    definition: loadJsonContent('workflow-definition.json')
    parameters: {
      clientCode: { value: clientCode }
      storageAccountName: { value: storageAccountName }
      tableName: { value: tableName }
      aoaiEndpoint: { value: 'https://${foundryName}.openai.azure.com' }
      aoaiDeployment: { value: aoaiDeployment }
      aoaiApiVersion: { value: aoaiApiVersion }
      allowedGroups: { value: allowedGroups }
      allowedGroupNames: { value: map(allowedGroups, g => g.name) }
    }
  }
}

resource tableRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (createRoleAssignments) {
  name: guid(storageAccount.id, logicAppName, storageTableDataContributorRoleId)
  scope: storageAccount
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', storageTableDataContributorRoleId)
    principalId: logicApp.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource aoaiRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (createRoleAssignments) {
  name: guid(foundry.id, logicAppName, cognitiveServicesOpenAIUserRoleId)
  scope: foundry
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', cognitiveServicesOpenAIUserRoleId)
    principalId: logicApp.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

output logicAppName string = logicApp.name
output managedIdentityPrincipalId string = logicApp.identity.principalId
