// =====================================================================
// Module: DIAGNOSTIC WRITE-BACK Logic App -- V10 slice 6
// Every 2 minutes, takes the diagwriteback rows of ONE client (clientId) that an ITSM agent
// VALIDATED in the web app's Diagnostic and that were not executed yet (status = 'validated',
// executionStatus = '': filtered in the query, 50 per run at most) and, per row:
//   1. claims it (MERGE executionStatus=running, If-Match on its ETag): written at most once;
//   2. finds the incident by number in ServiceNow (svc_ke_itsm, password from Key Vault); an
//      incident that is no longer active is left alone ('inactive');
//   3. 'work_note': adds the note as an internal work note; 'handover': same note, and the incident
//      is assigned to the ITSM module's group (KE-Automation), whose poller picks it up -- the ITSM
//      action engine then proposes, an agent validates, its own executor acts;
//   4. writes executionStatus (success / not_found / inactive / dry_run / error) back into the row.
// One executor = one client's rows -> one ServiceNow instance: the web app shows the write-back
// panel only for the clients listed in config/diag-writeback.yaml.
// The note comes from the session's fiche and steps (orchestration/guide/writeback.py), never
// from what the user typed. The web app never writes to ServiceNow and holds no ServiceNow
// credential: it only records the agent's validated request.
//
// SEPARATE IDENTITY, least privilege: Storage Table Data Contributor on the diagwriteback TABLE
// only (not the account: diagsessions holds what users typed), Key Vault Secrets User on the
// ServiceNow password SECRET only (not the vault). Nothing else.
//
// dryRun=true (default): the incident is looked up, nothing is written; the row gets dry_run.
// Deployed again with dryRun=false, the dry_run rows validated in the last 2 days are written for
// real (older ones stay simulated). Workflow generated by gen_workflow.py.
//
//   az deployment group create -g rg-knowledgeengine-v9 --name diag-writeback \
//     --template-file itsm/writeback/main.bicep --parameters clientId=client-s dryRun=true
// =====================================================================

param location string = resourceGroup().location
param namePrefix string = 'knowledgeengine3'
param storageAccountName string = 'st${namePrefix}v9'
param tableName string = 'diagwriteback'

@description('The client whose validated rows this executor writes (PartitionKey of the table)')
param clientId string = 'client-s'
param keyVaultName string = 'kv-${namePrefix}-v9'
param snInstance string = 'dev374242'
param snUser string = 'svc_ke_itsm'
param snSecretName string = 'servicenow-svc-ke-itsm-password'

@description('ServiceNow group of the ITSM module (itsm/poll reads its queue)')
param handoverGroup string = 'KE-Automation'

@description('true = the incident is looked up, nothing is written to ServiceNow')
param dryRun bool = true

param startEnabled bool = true
param createRoleAssignments bool = true

var logicAppName = 'logic-diag-writeback-${clientId}'
var storageTableDataContributorRoleId = '0a9a7e1f-b9d0-4cc4-a60d-0319b160aaa3'
var keyVaultSecretsUserRoleId = '4633458b-17de-408a-b874-0445c86b69e6'

resource storageAccount 'Microsoft.Storage/storageAccounts@2023-01-01' existing = {
  name: storageAccountName
}

resource tableService 'Microsoft.Storage/storageAccounts/tableServices@2023-01-01' existing = {
  parent: storageAccount
  name: 'default'
}

resource writebackTable 'Microsoft.Storage/storageAccounts/tableServices/tables@2023-01-01' = {
  parent: tableService
  name: tableName
}

resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' existing = {
  name: keyVaultName
}

resource snSecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' existing = {
  parent: keyVault
  name: snSecretName
}

resource logicApp 'Microsoft.Logic/workflows@2019-05-01' = {
  name: logicAppName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    state: startEnabled ? 'Enabled' : 'Disabled'
    definition: loadJsonContent('workflow-definition.json')
    parameters: {
      storageAccountName: { value: storageAccountName }
      tableName: { value: tableName }
      clientId: { value: clientId }
      snInstance: { value: snInstance }
      snUser: { value: snUser }
      keyVaultName: { value: keyVaultName }
      snSecretName: { value: snSecretName }
      handoverGroup: { value: handoverGroup }
      dryRun: { value: dryRun }
    }
  }
  dependsOn: [
    writebackTable
  ]
}

resource tableRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (createRoleAssignments) {
  name: guid(writebackTable.id, logicAppName, storageTableDataContributorRoleId)
  scope: writebackTable
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', storageTableDataContributorRoleId)
    principalId: logicApp.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource kvRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (createRoleAssignments) {
  name: guid(snSecret.id, logicAppName, keyVaultSecretsUserRoleId)
  scope: snSecret
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', keyVaultSecretsUserRoleId)
    principalId: logicApp.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

output logicAppName string = logicApp.name
output managedIdentityPrincipalId string = logicApp.identity.principalId
